# Generated by Django 2.0.1 on 2018-03-07 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180307_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 9, 26, 57, 16387, tzinfo=utc)),
        ),
    ]
