# Generated by Django 2.0.1 on 2018-03-07 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180307_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
