# Generated by Django 2.0.1 on 2018-03-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180307_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='unit_name',
            field=models.CharField(default='--', max_length=200),
        ),
    ]
